call plug#begin('~/.config/nvim/autoload/plugged')
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'preservim/nerdtree'    
	Plug 'preservim/nerdcommenter'
	Plug 'ayu-theme/ayu-vim'
	Plug 'jiangmiao/auto-pairs'
	Plug 'mattn/emmet-vim'
call plug#end()
